// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | "/"
    | "/_locales/en/messages.json"
    | "/_locales/zh/messages.json"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/icon/128.png"
    | "/icon/16.png"
    | "/icon/32.png"
    | "/icon/48.png"
    | "/icon/96.png"
    | "/images/jan.png"
    | "/images/lmstudio.png"
    | "/images/ollama.png"
    | "/images/scarlett-handshake.png"
    | "/images/scarlett-holding-bookmark.png"
    | "/images/scarlett-holding-dress.png"
    | "/lottie/happy.json"
    | "/lottie/neutral.json"
    | "/lottie/sad.json"
    | "/lottie/slightly-frowning.json"
    | "/lottie/slightly-happy.json"
    | "/newtab.html"
    | "/offscreen.html"
    | "/onboarding.html"
    | "/popup.html"
    | "/settings.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
