CREATE TABLE IF NOT EXISTS test_items (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL
); 

-- Table for storing clipped web pages
CREATE TABLE IF NOT EXISTS clips (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    url TEXT NOT NULL UNIQUE, -- Ensure URLs are unique
    clipped_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP -- Record when it was clipped
); 

-- Table for storing user LLM/Provider configuration (single row)
CREATE TABLE IF NOT EXISTS user_configuration (
    id INTEGER PRIMARY KEY DEFAULT 1, -- Ensure only one row
    config_json TEXT NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); 